INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Marc','Läufer','60327','Münchnerstraße 7','Frankfurt am Main','069 2475169');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('André','Müller','60606','Merkurweg 5','Frankfurt am Main ','069 51322845');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Ingrid','Baus','44805','Landsweg 82','Bochum','0234 2146422');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Stefanie','Steger','70173','Alleenring 75','Stuttgart','0711 52369');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Carl','Thore','80331','Tannenweg 4','München','089 512265');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Karsten ','Eichenhauer','86150','Elisabethenstraße 18','Augsburg','0821 2341678');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Elena','Lesch','93047','Freiherr-vom-Stein-Straße 66','Regensburg','0941 97436');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Roland','Fuss','44135','Bahnhofstraße 61','Dortmud','0231 464564');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Erica','Seguin','53111','Am Teichgraben 15','Bonn','0228 96457');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Angela','Burghardt','50667','Saalstraße 9','Köln','0221 674511');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Adrian','Kress','10115','Fürstengraben 11','Berlin','030 945612');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Julius','Krümpelmann','20038','Bachstraße 32','Hamburg','040 896622');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Rahel','Förtsch','24103','Talstraße 22','Kiel','0431 55446');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Claudia','Homann','56203','Lutherstraße 32','Höhr-Grenzhausen','02624 5544177');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Marius','Hasanovic','56068','Weinbergstraße 13','Koblenz','0261 6251846');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Eva','Meise','63739','Pfaffenstieg 32','Aschaffenburg','06021 548825');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Ann-Kathrin','Marks','91586','Lommerweg 1','Lichtenau, Mittelfranken','09827 54561');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Dario','Orlov','55469','Südring 43','Nannhausen','06761 6576');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Gabriela','Edis','56133','Reichenbachstraße 34','Fachbach','02603 42139');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Lothar','Klause','89429','Hohe Straße 33','Bachhagel','09077 69547');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Gustav','Gampe','24376','Brauereistraße 6','Rabel','04643 8566');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Christine','Münzberg','75365','Straße des 17. Juni 36','Calw','07051 854221');
INSERT INTO PERSON ("first_name", "last_name", "postal_code", "street", "city", "phone_number") VALUES ('Ilona','Haas ','06386','Zwickauerstraße 30','Quellendorf','034977 666789');


INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(1 ,'Äpfel; Butter; Zucker; Mehl; Eier (10, bio); 1 Tafel Schokolade','Erdnüsse',true,'Bar',10);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(2,'Toilettenpapier','Honig',false,'Bar',5);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(3,'400g gemischtes Hack, Zucchini, Toastbrot','keine',true,'PayPal',10);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(4,'Rotwein, Milch, Brot, Sahne, 1kg Kartoffeln','Gluten',true,'Bar',15);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(5,'Brotaufstrich, Margerine, Orangen','vegan',false,'PayPal',5);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(6,'Damenbinden, Tampons, Rasierklingen, Windeln Gr.4','keine',true,'Bar',30);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(7,'Essig, Öl, Kopfsalat, 2 Birnen, Gorgonzola','Gluten',true,'Bar',20);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(8,'Brot, Butter, Wurst, Käse, Milch, Bananen','Gluten',false,'PayPal',15);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(9,'Salami, Zwiebeln, 2 Pck Pasta, Mandarinen','Schweinefleisch',true,'Bar',15);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(10,'Obst, Gemüse, 2kg Kartoffeln','Trauben',true,'PayPal',15);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(11,'Desinfektionsspray, Chardonnay, Käse, Walnüsse','Nüsse',false,'Bar',40);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(12,'Erdnussbutter, Toast, Marmelade','keine',true,'Bar',10);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(13,'Knäckebrot, Frischkäse, Räucherlachs','keine',true,'PayPal',15);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(14,'Orangensaft, 10 Eier, Brötchen','Laktose',false,'Bar',10);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(15,'4 Äpfel, 2 Bananen, 1 Butter, 2 Sahne, 6 Eier, 1 Milch, kl. Brot','keine',true,'PayPal',25);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(16,'300g Schweinegulasch, Paprikaschoten (2), 4 Orangen, 6 Äpfel, 1 Pck Reis','keine',true,'Bar',25);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(17,'Butter, Eier,  Kringel Fleischwurst, zwei Packungen Orangensaft, einen Weißkohl, eine Packung Mehl, 1 Kilo Karotten. ','keine',false,'PayPal',20);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(18,'500g Kaffee (Filterkaffee), Kekse, Trauben, Milch','Diabetiker',true,'PayPal',10);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(19,'2 Tafeln dunkle Schokolade, Äpfel, 2kg Kartoffeln, etwas Kalbsleberwurst','keine',true,'Bar',20);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(20,'Bandnudeln, Sahne, C250g Champignons, Vollkornmehl (1kg)','Gluten',false,'PayPal',20);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(21,'TK-Spinat, kl. Pck.  Fischstäbchen, 2kg Kartoffeln, Zwiebeln','Laktose',true,'Bar',15);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(22,'Zucker, Mehl, Erbsen (TK), Dosentomaten (2), Nudeln (1)','keine',true,'Bar',20);
INSERT INTO requester (person_id, shopping_list, dietary_requirements, premium, payment_method, max_amount) VALUES(23,'Karotten (1kg), Kopfsalat (1), Birnen, Grapefruit (2)','keine',false,'PayPal',10);
